version: '3.8'

services:
  nav2-dev:
    build:
      context: .
      dockerfile: Dockerfile
    
    image: nav2-dev_container:latest
    container_name: nav2_dev_container
    
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - DISPLAY=:1
      - VNC_PORT=5900
      - VNC_RESOLUTION=1920x1080
      - VNC_DPI=96
      - VNC_DEPTH=24
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=1
    
    # Expose VNC port
    ports:
      # Optional: noVNC web interface
      - "6080:6080"
    
    volumes:
      - ../:/home/ubuntu/nav2_ws/src/nav2_dev/
    
    network_mode: host
    stdin_open: true
    tty: true
    command: /bin/bash